CREATE TABLE "User" (
  "id" TEXT PRIMARY KEY,
  "clerkId" TEXT NOT NULL UNIQUE,
  "email" TEXT NOT NULL UNIQUE,
  "name" TEXT,
  "role" TEXT NOT NULL DEFAULT 'free',
  "planId" TEXT,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Plan" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE,
  "slug" TEXT NOT NULL UNIQUE,
  "description" TEXT,
  "monthlyQuota" INTEGER NOT NULL DEFAULT 1000,
  "rateLimit" INTEGER NOT NULL DEFAULT 10,
  "maxTokens" INTEGER NOT NULL DEFAULT 2000,
  "allowedModels" TEXT[] NOT NULL DEFAULT '{}',
  "features" TEXT[] NOT NULL DEFAULT '{}',
  "priceInCents" INTEGER NOT NULL DEFAULT 0,
  "isActive" BOOLEAN NOT NULL DEFAULT TRUE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "ApiKey" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT NOT NULL,
  "key" VARCHAR(255) NOT NULL UNIQUE,
  "userId" TEXT,
  "planId" TEXT NOT NULL,
  "isActive" BOOLEAN NOT NULL DEFAULT TRUE,
  "lastUsedAt" TIMESTAMP,
  "expiresAt" TIMESTAMP,
  "quotaResetAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "usageThisMonth" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "UsageLog" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT,
  "apiKeyId" TEXT,
  "model" TEXT NOT NULL,
  "inputTokens" INTEGER NOT NULL,
  "outputTokens" INTEGER NOT NULL,
  "totalTokens" INTEGER NOT NULL,
  "durationMs" INTEGER NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'success',
  "errorMessage" TEXT,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Model" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE,
  "provider" TEXT NOT NULL,
  "description" TEXT,
  "contextWindow" INTEGER NOT NULL DEFAULT 4096,
  "costPer1k" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  "isActive" BOOLEAN NOT NULL DEFAULT TRUE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "User" ADD CONSTRAINT "User_planId_fkey" FOREIGN KEY ("planId") REFERENCES "Plan" ("id") ON DELETE SET NULL;
ALTER TABLE "ApiKey" ADD CONSTRAINT "ApiKey_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE;
ALTER TABLE "ApiKey" ADD CONSTRAINT "ApiKey_planId_fkey" FOREIGN KEY ("planId") REFERENCES "Plan" ("id") ON DELETE CASCADE;
ALTER TABLE "UsageLog" ADD CONSTRAINT "UsageLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE SET NULL;
ALTER TABLE "UsageLog" ADD CONSTRAINT "UsageLog_apiKeyId_fkey" FOREIGN KEY ("apiKeyId") REFERENCES "ApiKey" ("id") ON DELETE SET NULL;

CREATE INDEX "UsageLog_userId_idx" ON "UsageLog" ("userId");
CREATE INDEX "UsageLog_apiKeyId_idx" ON "UsageLog" ("apiKeyId");
CREATE INDEX "UsageLog_createdAt_idx" ON "UsageLog" ("createdAt");
